apiVersion: v1
kind: Secret
metadata:
  name: db-erd-temp-auth
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: dbuser
  password: temp-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-erd-temp
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  
  bootstrap:
    initdb:
      database: mydb
      owner: dbuser
      secret:
        name: db-erd-temp-auth
  
  storage:
    size: 1Gi
  
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
